# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Paul Kim"
email: "thekpaul@outlook.com"
description: "The Official Portfolio of Paul Kim the Programmer"
baseurl: ""
url: "https://thekpaul.github.io"

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_username: "thekpaul"
twitter_username:
facebook_URL: "https://www.facebook.com/profile.php?id=100023550311260"
instagram_username: "the_kpaul"

# Build settings
markdown: kramdown
