# Site settings
title: "Paul Kim"
email: "thekpaul@outlook.com"
description: "A Free Developer"
baseurl: "alpha"
url: "https://thekpaul.github.io/"
permalink: "/:path"

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_url: "https://www.github.com/thekpaul"
facebook_url: "https://www.facebook.com/profile.php?id=100023550311260"
instagram_username: "https://www.instagram.com/the_kpaul"

# Build settings
markdown: kramdown

# Language Settings
defaults:
  -
    scope:
      path: "en"
      type: "pages"
    values:
      lang: "en"
  -
    scope:
      path: "ko"
      type: "pages"
    values:
      lang: "ko"
