# Site settings
title: "Paul Kim"
email: "thekpaul@outlook.com"
description: "A Free Developer"
baseurl: ""
url: "https://thekpaul.dev/"
home: "https://thekpaul.dev/" # The Full URL for Site HOME
permalink: ":path"

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_url: "https://www.github.com/thekpaul"
facebook_url: "https://fb.me/thekpaul/"
instagram_url: "https://www.instagram.com/thekpaul.dev"
linkedin_url: "https://www.linkedin.com/in/thekpaul"
stackoverflow_url: "https://stackoverflow.com/users/6834127/paul-kim"
stackexchange_url: "https://stackexchange.com/users/9195167/paul-kim"
devto_url: "https://dev.to/thekpaul"

# Build settings
markdown: kramdown

# Language Settings
defaults:
  -
    scope:
      path: "en"
      type: "pages"
    values:
      layout: "page"
      lang: "en"
  -
    scope:
      path: "en"
      type: "posts"
    values:
      layout: "post"
      lang: "en"
      author: "Paul Kim"
  -
    scope:
      path: "ko"
      type: "pages"
    values:
      layout: "page"
      lang: "ko"
  -
    scope:
      path: "ko"
      type: "posts"
    values:
      layout: "post"
      lang: "ko"
      author: "Paul Kim"

# Settings for Posts
collections:
  posts:
    output: true
    permalink: /:categories/:title
