# Site settings
title: "Paul Kim"
email: "thekpaul@outlook.com"
description: "A Free Developer"
baseurl: ""
url: "https://thekpaul.github.io/"
home: "https://thekpaul.github.io/" # The Full URL for Site HOME
permalink: ":path"

# Logo settings
logo-image-url:
font-awesome-icon-logo:

# Social settings
github_url: "https://www.github.com/thekpaul"
facebook_url: "https://www.facebook.com/profile.php?id=100023550311260"
instagram_url: "https://www.instagram.com/the_kpaul"

# Build settings
markdown: kramdown

# Language Settings
defaults:
  -
    scope:
      path: "en"
      type: "pages"
    values:
      layout: "page"
      lang: "en"
  -
    scope:
      path: "en"
      type: "posts"
    values:
      layout: "post"
      lang: "en"
      author: "Paul Kim"
  -
    scope:
      path: "ko"
      type: "pages"
    values:
      layout: "page"
      lang: "ko"
  -
    scope:
      path: "ko"
      type: "posts"
    values:
      layout: "post"
      lang: "ko"
      author: "Paul Kim"
